// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/t-moor/slow-query-detector/internal/query/service/dto"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// FindQueries provides a mock function with given fields: ctx, input
func (_m *Service) FindQueries(ctx context.Context, input dto.FindQueriesInput) (dto.FindQueriesOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 dto.FindQueriesOutput
	if rf, ok := ret.Get(0).(func(context.Context, dto.FindQueriesInput) dto.FindQueriesOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dto.FindQueriesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.FindQueriesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
