// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repository "github.com/t-moor/slow-query-detector/internal/query/repository"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindQueries provides a mock function with given fields: ctx, criteria
func (_m *Repository) FindQueries(ctx context.Context, criteria repository.FindQueriesCriteria) (repository.FindQueriesResults, error) {
	ret := _m.Called(ctx, criteria)

	var r0 repository.FindQueriesResults
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindQueriesCriteria) repository.FindQueriesResults); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.FindQueriesResults)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repository.FindQueriesCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
